package proyectosmm;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 * Ventana que permite al usuario escribir las dimensiones del lienzo a crear
 * @author David Infante Casas
 */
public class TamLienzo extends javax.swing.JDialog {

    /**
     * Crea un nuevo TamLienzo
     * @param parent Frame desde el que se crea
     * @param modal Especifica si el dialog bloquea o no entrada del usuario
     */
    public TamLienzo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.addWindowListener (new WindowAdapter() {
            @Override
            public void windowClosing (WindowEvent e) {
                System.exit(0);
            }
        });
    }
    
    /**
     * Devuelve las dimensiones X e Y introducidas por el usuario
     * @return String que contiene las dimensiones separadas por un guión "-"
     */
    public String obtenerDimensiones() {
        this.setVisible(true);
        return jTextFieldX.getText() + "-" + jTextFieldY.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelInstr = new javax.swing.JLabel();
        jPanelDimensiones = new javax.swing.JPanel();
        jLabelX = new javax.swing.JLabel();
        jTextFieldX = new javax.swing.JTextField();
        jLabelY = new javax.swing.JLabel();
        jTextFieldY = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();

        setResizable(false);

        jLabelInstr.setText("Seleccione las dimensiones del lienzo:");
        jLabelInstr.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabelInstr, java.awt.BorderLayout.NORTH);

        jPanelDimensiones.setLayout(new javax.swing.BoxLayout(jPanelDimensiones, javax.swing.BoxLayout.LINE_AXIS));

        jLabelX.setText("X:");
        jLabelX.setToolTipText("X");
        jPanelDimensiones.add(jLabelX);

        jTextFieldX.setText("600");
        jPanelDimensiones.add(jTextFieldX);

        jLabelY.setText("Y:");
        jLabelY.setToolTipText("Y");
        jPanelDimensiones.add(jLabelY);

        jTextFieldY.setText("400");
        jPanelDimensiones.add(jTextFieldY);

        getContentPane().add(jPanelDimensiones, java.awt.BorderLayout.CENTER);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setToolTipText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelInstr;
    private javax.swing.JLabel jLabelX;
    private javax.swing.JLabel jLabelY;
    private javax.swing.JPanel jPanelDimensiones;
    private javax.swing.JTextField jTextFieldX;
    private javax.swing.JTextField jTextFieldY;
    // End of variables declaration//GEN-END:variables
}
